### ISSUE TITLE
"IndexError: list index out of range" in FbTime.span_meta_to_date

### ISSUE THREAD

**Issue by dylanOshima** [Buroni/booksoup#1] opened 2018-04-16 18:57 UTC
There seems to be a problem with the code on `line 68` in `FbTime.py`. The problem is in the array call for `date_arr[2]`. It seems to assume that the array is longer then 2 but in my case the array is only of length 2. 

What is happening in these lines?

**Comment by Buroni** [comment] 2018-04-16 20:07
Hi Dylan, thanks for raising the issue. `span_meta_to_date` takes an argument `span_str` as an argument. Could you provide the contents of `span_str` where the `IndexError` occurs? For example it should be something like "Wednesday, 25 July 2012 at 22:52 UTC+02"

**Comment by dylanOshima** [comment] 2018-04-18 11:09
No problem.

It says: `Friday, March 30, 2018 at 10:18pm UTC+02`. It seems the data formatting is slightly different with the March.

**Comment by Buroni** [comment] 2018-04-18 12:02
@dylanOshima Okay, the problem is caused by a second comma after "March 30". Fix involves removing the second comma if it exists. Please pull the master branch and confirm that the problem is fixed, then I'll close the issue. Thank you!

**Closed as completed** 2018-04-22 19:36 UTC
Labels: bug
